import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/shared/navbar/Navbar';
import ConditionalNavbar from '@/components/shared/navbar/ConditionalNavbar';
import { NotificationsProvider } from '@/context/NotificationContext'; // ✅ استدعاء البروفايدر

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="ltr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* ✅ غلف كل محتوى الموقع بالبروفايدر */}
        <NotificationsProvider>
          <ConditionalNavbar />
          <main>{children}</main>
        </NotificationsProvider>
      </body>
    </html>
  );
}